#!/bin/bash

for src in $(find . -type f -name "*.tm"); do
    trimmed="${src%???}"
    echo $trimmed
    typst c ./turing-demo-collection.typ --root .. --input source="$src" "$trimmed.pdf"
done

# Clean files automatically generated by VSCode
rm ./turing-demo-collection.pdf
rm ../turing.pdf

typst c ./turing-demo-collection.typ --root .. --input source="./zero.tm" "zero.png"
